USE ROLE      IDENTIFIER('RL_DWH_T_ELT');
  USE WAREHOUSE IDENTIFIER('WH_DWH_T_ELT');
  USE DATABASE  IDENTIFIER('DB_DWH_T');

TRUNCATE TABLE "DB_DWH_T"."DWH_1_RAW"."RAW_JIRA_BOARDS";
INSERT INTO "DB_DWH_T"."DWH_1_RAW"."RAW_JIRA_BOARDS" (META_BESTANDSNAAM, META_RIJNUMMER, C001, C002, C003) 
                                              VALUES ('JIRA_BOARDS__20210509.csv', '1', 'BOARDS_ID', 'BOARDS_KEY', 'BOARDS_TYPE');

