
-- Prerequisites
USE ROLE   SYSADMIN;
  USE DATABASE UTIL_DB;
  USE SCHEMA PUBLIC;
-- Grant all the rights to the public schema
USE ROLE   SYSADMIN;
  GRANT USAGE ON SCHEMA UTIL_DB.PUBLIC TO ROLE PUBLIC;

-- Prerequisites
USE ROLE SECURITYADMIN;
  USE DATABASE UTIL_DB;
USE ROLE PUBLIC;
-- Execute
USE ROLE SECURITYADMIN;
  USE DATABASE UTIL_DB;
  GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA PUBLIC TO ROLE PUBLIC;
  GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PUBLIC TO ROLE PUBLIC;
