/*
 * Created for the purpose of unit-testing.
 * We advise that data manipulation operations should managed by an ELT tool.
 */
USE ROLE      IDENTIFIER('RL_DWH_T_ELT');
  USE WAREHOUSE IDENTIFIER('WH_DWH_T_ELT');
  USE DATABASE  IDENTIFIER('DB_DWH_T');
  USE SCHEMA    IDENTIFIER('DWH_0_META');

  TRUNCATE TABLE "DB_DWH_T"."DWH_0_META"."META_DATA_PER_SOURCE";
  INSERT INTO    "DB_DWH_T"."DWH_0_META"."META_DATA_PER_SOURCE" VALUES ('JIRA_BOARDS', 'RAW_JIRA_BOARDS', 'REF_JIRA_BOARDS', 'JIRA_BOARDS_*');
  INSERT INTO    "DB_DWH_T"."DWH_0_META"."META_DATA_PER_SOURCE" VALUES ('JIRA_SPRINTS', 'RAW_JIRA_SPRINTS', 'REF_JIRA_SPRINTS', 'JIRA_SPRINTS_.*');

