name: Acheron Database Manager CI/CD
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    container: 
      image: acheronbv/acheron-database-manager:latest-1.3.35
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run linter step
        shell: bash
        run: |
          echo "Linting ..."
          python $(ls -d "/usr/local/lib/"python*/ | tail -1)/site-packages/opt/acheron/lint.py "$@"
  
  templater_dryrun:
    needs: linter
    runs-on: ubuntu-latest
    container: 
      image: acheronbv/acheron-database-manager:latest-1.3.35
    env:
      ACH_DEPLOY_USERNAME: ${{ secrets.ACH_DEPLOY_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      CI_REPOSITORY_URL: "git@github.com:rdaalman-ach/acheron-adm-demo-klant.git"
      ACHERON_GIT_PORT: 22
      GIT_COMMIT_COMMITTER_EMAIL: "rob@acheron.cloud"
    steps:
      - name: Run templater step
        shell: bash
        run: |
          echo "Templating ...."
          eval $(ssh-agent -s)
          python $(ls -d "/usr/local/lib/"python*/ | tail -1)/site-packages/opt/acheron/template.py "$@" adm-demo-environment --print-generated-contents --delegate-repo-push
        
  templater:
    needs: templater_dryrun
    runs-on: ubuntu-latest
    container: 
      image: acheronbv/acheron-database-manager:latest-1.3.35
    env:
      ACH_DEPLOY_USERNAME: ${{ secrets.ACH_DEPLOY_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      CI_REPOSITORY_URL: "git@github.com:rdaalman-ach/acheron-adm-demo-klant.git"
      ACHERON_GIT_PORT: 22
      GIT_COMMIT_COMMITTER_EMAIL: "info@acheron.cloud"
    steps:
      - name: Run templater step
        shell: bash
        run: |
          echo "Templating ...."
          eval $(ssh-agent -s)
          python $(ls -d "/usr/local/lib/"python*/ | tail -1)/site-packages/opt/acheron/template.py "$@" adm-demo-environment
  
  executer:
    needs: templater
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Commit new Container run results')"
    container: 
      image: acheronbv/acheron-database-manager:latest-1.3.35
    env:
      ACHERON_SNOWSQL_ENDPOINT: fill-with-endpoint
      ACHERON_SNOWSQL_PASS: fill-with-password
      ACHERON_SNOWSQL_USER: fill-with-user
      ACH_DEPLOY_USERNAME: ${{ secrets.ACH_DEPLOY_USERNAME }}
      CI_REPOSITORY_URL: "git@github.com:rdaalman-ach/acheron-adm-demo-klant.git"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ACHERON_GIT_PORT: 22
      GIT_COMMIT_COMMITTER_EMAIL: "info@acheron.cloud"
    steps:
      - name: Run executer
        shell: bash
        run: | 
          echo "Executing to Snowflake"
          eval $(ssh-agent -s)
          python $(ls -d "/usr/local/lib/"python*/ | tail -1)/site-packages/opt/acheron/execute.py "$@" adm-demo-environment -v
        
